build: fix TypeScript issues
src/app/modules/playlist/components/organisms/PlaylistShortcut.spec.ts:22:15 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").DefineComponent<{ cover: { type: StringConstructor; required: true; }; title: { type: StringConstructor; required: true; }; description: { type: Strin
gConstructor; required: true; }; }, ... 10 more ..., {}>' is not assignable to parameter of type 'import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").DefineComponent<{ cover: { type: StringConstructor; required: true; }; tit
le: { type: StringConstructor; required: true; }; description: { type: StringConstructor; required: true; }; }, ... 10 more ..., {}>'.
      Type 'DefineComponent<{ cover: { type: StringConstructor; required: true; }; title: { type: StringConstructor; required: true; }; description: { type: StringConstructor; required: true; }; }, ... 10 more ..., {}>' is not assignable to type 'ComponentPublic
InstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}> & VNodeProps & AllowedComponentProps &
ComponentCustomProps, never>; ... 10 mor...'.
        Type '{ $: import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<...> & import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/di
st/runtime-core").VNodeProps & import("C:/Users/MCMod/www/ewokify-app...' is not assignable to type '{ $: import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<R
eadonly<...> & import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").VNodeProps & import("C:/Users/MCMod/www/ewokify-app...'. Two different types with this name exist, but they are unrelated.
          Type '{ $: import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<...> & import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/
dist/runtime-core").VNodeProps & import("C:/Users/MCMod/www/ewokify-app...' is not assignable to type '{ $: import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit
<Readonly<{ ...; } & ... 1 more ... & {}> & import("C:/Users/MCMod/www/ewokify-app/node_modules/@vue/runtime-core/dist/runtime-core").VNodeProps & import("C:/...'.
            Types of property '$options' are incompatible.
              Type 'ComponentOptionsBase<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}>, () => void, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, Record<...>,
 string, {}> & MergedComponentOptionsOverride' is not assignable to type 'ComponentOptionsBase<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}>, {}, {}, ComputedOptions, MethodOp
tions, ... 4 more ..., {}> & MergedComponentOptionsOverride'.
                Type 'ComponentOptionsBase<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}>, () => void, unknown, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, Record<...
>, string, {}> & MergedComponentOptionsOverride' is not assignable to type 'ComponentOptionsBase<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}>, {}, {}, ComputedOptions, Method
Options, ... 4 more ..., {}>'.
                  Types of property 'data' are incompatible.
                    Type '((this: CreateComponentPublicInstance<...>, vm: CreateComponentPublicInstance<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}>, {}, {}, {}, MethodOption
s, ComponentOptionsMixin, ... 11 more ..., {}>) => unknown) | undefined' is not assignable to type '((this: CreateComponentPublicInstance<...>, vm: CreateComponentPublicInstance<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { descriptio
n: string; title: string; cover: string; } & {}>, {}, {}, {}, MethodOptions, ComponentOptionsMixin, ... 11 more ..., {}>) => {}) | undefined'.
                      Type '(this: CreateComponentPublicInstance<...>, vm: CreateComponentPublicInstance<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; title: string; cover: string; } & {}>, {}, {}, {}, MethodOptio
ns, ComponentOptionsMixin, ... 11 more ..., {}>) => unknown' is not assignable to type '(this: CreateComponentPublicInstance<...>, vm: CreateComponentPublicInstance<Readonly<{ cover?: unknown; title?: unknown; description?: unknown; } & { description: string; ti
tle: string; cover: string; } & {}>, {}, {}, {}, MethodOptions, ComponentOptionsMixin, ... 11 more ..., {}>) => {}'.
                        Type 'unknown' is not assignable to type '{}'.

22             h(PlaylistShortcutItem, Album.args)
                 ~~~~~~~~~~~~~~~~~~~~

  node_modules/@vue/runtime-core/dist/runtime-core.d.ts:928:25
    928 export declare function h<P>(type: DefineComponent<P>, props?: (RawProps & P) | ({} extends P ? null : never), children?: RawChildren | RawSlots): VNode;
                                ~
    The last overload is declared here.